# Generated by Django 4.2.3 on 2023-07-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_movie_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
    ]
